version: '3.9'

services:
  migrate:
    image: "migrate/migrate"
    networks:
      - TurkNet
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:dodi@postgres_post:5432/cm?sslmode=disable", "up" ]
    depends_on:
      postgres_post:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres_post:
    image: postgres:16.3
    container_name: postgres_post
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dodi
      - POSTGRES_DB=cm
    networks:
      - TurkNet
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  turk-post:
    build: .
    ports:
      - 50055:50055
    networks:
      - TurkNet
    depends_on:
      postgres_post:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:50055 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  TurkNet:
    name: TurkNet
    driver: bridge

volumes:
  postgres_data:
