INSERT INTO countries (country, nationality, flag)
VALUES
    ('Turkey', 'Turkish', 'https://flagpedia.net/data/flags/h80/tr.png'),
    ('Azerbaijan', 'Azerbaijani', 'https://flagpedia.net/data/flags/h80/az.png'),
    ('Kazakhstan', 'Kazakh', 'https://flagpedia.net/data/flags/h80/kz.png'),
    ('Uzbekistan', 'Uzbek', 'https://flagpedia.net/data/flags/h80/uz.png'),
    ('Turkmenistan', 'Turkmen', 'https://flagpedia.net/data/flags/h80/tm.png'),
    ('Kyrgyzstan', 'Kyrgyz', 'https://flagpedia.net/data/flags/h80/kg.png'),
    ('Tatarstan', 'Tatar', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('Bashkortostan', 'Bashkir', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('Chuvashia', 'Chuvash', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('Altai', 'Altai', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('Tuva', 'Tuvan', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('Khakassia', 'Khakas', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('Crimea', 'Crimean Tatar', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('China', 'Uyghur', 'https://flagpedia.net/data/flags/h80/cn.png'),
    ('Gagauzia', 'Gagauz', 'https://flagpedia.net/data/flags/h80/md.png'),
    ('Karakalpakstan', 'Karakalpak', 'https://flagpedia.net/data/flags/h80/uz.png'),
    ('Afghanistan', 'Turkmen', 'https://flagpedia.net/data/flags/h80/af.png'),
    ('Iraq', 'Iraqi Turkmen', 'https://flagpedia.net/data/flags/h80/iq.png'),
    ('Syria', 'Syrian Turkmen', 'https://flagpedia.net/data/flags/h80/sy.png'),
    ('Georgia', 'Meskhetian Turk', 'https://flagpedia.net/data/flags/h80/ge.png'),
    ('Hungary', 'Kipchak Turkic', 'https://flagpedia.net/data/flags/h80/hu.png'),
    ('Mongolia', 'Kazakh', 'https://flagpedia.net/data/flags/h80/mn.png'),
    ('Russia', 'Nogai', 'https://flagpedia.net/data/flags/h80/ru.png'),
    ('Iran', 'Azerbaijani Turk', 'https://flagpedia.net/data/flags/h80/ir.png'),
    ('Cyprus', 'Turkish Cypriot', 'https://flagpedia.net/data/flags/h80/cy.png'),
    ('Bulgaria', 'Bulgarian Turk', 'https://flagpedia.net/data/flags/h80/bg.png'),
    ('Greece', 'Western Thrace Turk', 'https://flagpedia.net/data/flags/h80/gr.png'),
    ('North Macedonia', 'Macedonian Turk', 'https://flagpedia.net/data/flags/h80/mk.png'),
    ('Romania', 'Romanian Turk', 'https://flagpedia.net/data/flags/h80/ro.png'),
    ('Ukraine', 'Crimean Tatar', 'https://flagpedia.net/data/flags/h80/ua.png');
