// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.25.1
// source: Protocol-buffers/post/post.proto

package post

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PostService_CreatePost_FullMethodName               = "/post.PostService/CreatePost"
	PostService_UpdatePost_FullMethodName               = "/post.PostService/UpdatePost"
	PostService_GetPostByID_FullMethodName              = "/post.PostService/GetPostByID"
	PostService_ListPosts_FullMethodName                = "/post.PostService/ListPosts"
	PostService_DeletePost_FullMethodName               = "/post.PostService/DeletePost"
	PostService_RemoveImageFromPost_FullMethodName      = "/post.PostService/RemoveImageFromPost"
	PostService_GetPostByCountry_FullMethodName         = "/post.PostService/GetPostByCountry"
	PostService_AddLikePost_FullMethodName              = "/post.PostService/AddLikePost"
	PostService_DeleteLikePost_FullMethodName           = "/post.PostService/DeleteLikePost"
	PostService_AddLikeComment_FullMethodName           = "/post.PostService/AddLikeComment"
	PostService_DeleteLikeComment_FullMethodName        = "/post.PostService/DeleteLikeComment"
	PostService_GetPostLikeCount_FullMethodName         = "/post.PostService/GetPostLikeCount"
	PostService_GetCommentLikeCount_FullMethodName      = "/post.PostService/GetCommentLikeCount"
	PostService_GetUsersWhichLikePost_FullMethodName    = "/post.PostService/GetUsersWhichLikePost"
	PostService_GetUsersWhichLikeComment_FullMethodName = "/post.PostService/GetUsersWhichLikeComment"
	PostService_CreateComment_FullMethodName            = "/post.PostService/CreateComment"
	PostService_UpdateComment_FullMethodName            = "/post.PostService/UpdateComment"
	PostService_GetCommentByID_FullMethodName           = "/post.PostService/GetCommentByID"
	PostService_GetCommentByUsername_FullMethodName     = "/post.PostService/GetCommentByUsername"
	PostService_ListComments_FullMethodName             = "/post.PostService/ListComments"
	PostService_DeleteComment_FullMethodName            = "/post.PostService/DeleteComment"
	PostService_GetCommentByPostID_FullMethodName       = "/post.PostService/GetCommentByPostID"
	PostService_GetAllUserComments_FullMethodName       = "/post.PostService/GetAllUserComments"
	PostService_GetMostlikeCommentPost_FullMethodName   = "/post.PostService/GetMostlikeCommentPost"
)

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostServiceClient interface {
	// post
	CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*PostResponse, error)
	UpdatePost(ctx context.Context, in *UpdateAPost, opts ...grpc.CallOption) (*PostResponse, error)
	GetPostByID(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*PostResponse, error)
	ListPosts(ctx context.Context, in *PostList, opts ...grpc.CallOption) (*PostListResponse, error)
	DeletePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*Message, error)
	RemoveImageFromPost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*PostListResponse, error)
	GetPostByCountry(ctx context.Context, in *PostCountry, opts ...grpc.CallOption) (*PostListResponse, error)
	// like
	AddLikePost(ctx context.Context, in *LikePost, opts ...grpc.CallOption) (*LikePost, error)
	DeleteLikePost(ctx context.Context, in *LikeId, opts ...grpc.CallOption) (*Message, error)
	AddLikeComment(ctx context.Context, in *LikeId, opts ...grpc.CallOption) (*PostListResponse, error)
	DeleteLikeComment(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Message, error)
	GetPostLikeCount(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*Message, error)
	GetCommentLikeCount(ctx context.Context, in *Like, opts ...grpc.CallOption) (*PostListResponse, error)
	GetUsersWhichLikePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*PostListResponse, error)
	GetUsersWhichLikeComment(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*PostListResponse, error)
	// comments
	CreateComment(ctx context.Context, in *CommentPost, opts ...grpc.CallOption) (*CommentResponse, error)
	UpdateComment(ctx context.Context, in *UpdateAComment, opts ...grpc.CallOption) (*CommentResponse, error)
	GetCommentByID(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*CommentResponse, error)
	GetCommentByUsername(ctx context.Context, in *UserPostId, opts ...grpc.CallOption) (*CommentResponse, error)
	ListComments(ctx context.Context, in *CommentList, opts ...grpc.CallOption) (*Message, error)
	DeleteComment(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*Message, error)
	GetCommentByPostID(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*CommentResponse, error)
	GetAllUserComments(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*CommentAllResponse, error)
	GetMostlikeCommentPost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*CommentResponse, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, PostService_CreatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *UpdateAPost, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, PostService_UpdatePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostByID(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, PostService_GetPostByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListPosts(ctx context.Context, in *PostList, opts ...grpc.CallOption) (*PostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, PostService_ListPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, PostService_DeletePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) RemoveImageFromPost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*PostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, PostService_RemoveImageFromPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostByCountry(ctx context.Context, in *PostCountry, opts ...grpc.CallOption) (*PostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, PostService_GetPostByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) AddLikePost(ctx context.Context, in *LikePost, opts ...grpc.CallOption) (*LikePost, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikePost)
	err := c.cc.Invoke(ctx, PostService_AddLikePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteLikePost(ctx context.Context, in *LikeId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, PostService_DeleteLikePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) AddLikeComment(ctx context.Context, in *LikeId, opts ...grpc.CallOption) (*PostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, PostService_AddLikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteLikeComment(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, PostService_DeleteLikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetPostLikeCount(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, PostService_GetPostLikeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetCommentLikeCount(ctx context.Context, in *Like, opts ...grpc.CallOption) (*PostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, PostService_GetCommentLikeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetUsersWhichLikePost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*PostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, PostService_GetUsersWhichLikePost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetUsersWhichLikeComment(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*PostListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostListResponse)
	err := c.cc.Invoke(ctx, PostService_GetUsersWhichLikeComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateComment(ctx context.Context, in *CommentPost, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, PostService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdateComment(ctx context.Context, in *UpdateAComment, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, PostService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetCommentByID(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, PostService_GetCommentByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetCommentByUsername(ctx context.Context, in *UserPostId, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, PostService_GetCommentByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListComments(ctx context.Context, in *CommentList, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, PostService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteComment(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, PostService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetCommentByPostID(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, PostService_GetCommentByPostID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetAllUserComments(ctx context.Context, in *CommentId, opts ...grpc.CallOption) (*CommentAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentAllResponse)
	err := c.cc.Invoke(ctx, PostService_GetAllUserComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetMostlikeCommentPost(ctx context.Context, in *PostId, opts ...grpc.CallOption) (*CommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, PostService_GetMostlikeCommentPost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
// All implementations must embed UnimplementedPostServiceServer
// for forward compatibility
type PostServiceServer interface {
	// post
	CreatePost(context.Context, *Post) (*PostResponse, error)
	UpdatePost(context.Context, *UpdateAPost) (*PostResponse, error)
	GetPostByID(context.Context, *PostId) (*PostResponse, error)
	ListPosts(context.Context, *PostList) (*PostListResponse, error)
	DeletePost(context.Context, *PostId) (*Message, error)
	RemoveImageFromPost(context.Context, *Post) (*PostListResponse, error)
	GetPostByCountry(context.Context, *PostCountry) (*PostListResponse, error)
	// like
	AddLikePost(context.Context, *LikePost) (*LikePost, error)
	DeleteLikePost(context.Context, *LikeId) (*Message, error)
	AddLikeComment(context.Context, *LikeId) (*PostListResponse, error)
	DeleteLikeComment(context.Context, *UserId) (*Message, error)
	GetPostLikeCount(context.Context, *PostId) (*Message, error)
	GetCommentLikeCount(context.Context, *Like) (*PostListResponse, error)
	GetUsersWhichLikePost(context.Context, *PostId) (*PostListResponse, error)
	GetUsersWhichLikeComment(context.Context, *CommentId) (*PostListResponse, error)
	// comments
	CreateComment(context.Context, *CommentPost) (*CommentResponse, error)
	UpdateComment(context.Context, *UpdateAComment) (*CommentResponse, error)
	GetCommentByID(context.Context, *CommentId) (*CommentResponse, error)
	GetCommentByUsername(context.Context, *UserPostId) (*CommentResponse, error)
	ListComments(context.Context, *CommentList) (*Message, error)
	DeleteComment(context.Context, *CommentId) (*Message, error)
	GetCommentByPostID(context.Context, *PostId) (*CommentResponse, error)
	GetAllUserComments(context.Context, *CommentId) (*CommentAllResponse, error)
	GetMostlikeCommentPost(context.Context, *PostId) (*CommentResponse, error)
	mustEmbedUnimplementedPostServiceServer()
}

// UnimplementedPostServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (UnimplementedPostServiceServer) CreatePost(context.Context, *Post) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedPostServiceServer) UpdatePost(context.Context, *UpdateAPost) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedPostServiceServer) GetPostByID(context.Context, *PostId) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostByID not implemented")
}
func (UnimplementedPostServiceServer) ListPosts(context.Context, *PostList) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPosts not implemented")
}
func (UnimplementedPostServiceServer) DeletePost(context.Context, *PostId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedPostServiceServer) RemoveImageFromPost(context.Context, *Post) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveImageFromPost not implemented")
}
func (UnimplementedPostServiceServer) GetPostByCountry(context.Context, *PostCountry) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostByCountry not implemented")
}
func (UnimplementedPostServiceServer) AddLikePost(context.Context, *LikePost) (*LikePost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLikePost not implemented")
}
func (UnimplementedPostServiceServer) DeleteLikePost(context.Context, *LikeId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLikePost not implemented")
}
func (UnimplementedPostServiceServer) AddLikeComment(context.Context, *LikeId) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLikeComment not implemented")
}
func (UnimplementedPostServiceServer) DeleteLikeComment(context.Context, *UserId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLikeComment not implemented")
}
func (UnimplementedPostServiceServer) GetPostLikeCount(context.Context, *PostId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostLikeCount not implemented")
}
func (UnimplementedPostServiceServer) GetCommentLikeCount(context.Context, *Like) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentLikeCount not implemented")
}
func (UnimplementedPostServiceServer) GetUsersWhichLikePost(context.Context, *PostId) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersWhichLikePost not implemented")
}
func (UnimplementedPostServiceServer) GetUsersWhichLikeComment(context.Context, *CommentId) (*PostListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersWhichLikeComment not implemented")
}
func (UnimplementedPostServiceServer) CreateComment(context.Context, *CommentPost) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedPostServiceServer) UpdateComment(context.Context, *UpdateAComment) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedPostServiceServer) GetCommentByID(context.Context, *CommentId) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentByID not implemented")
}
func (UnimplementedPostServiceServer) GetCommentByUsername(context.Context, *UserPostId) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentByUsername not implemented")
}
func (UnimplementedPostServiceServer) ListComments(context.Context, *CommentList) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedPostServiceServer) DeleteComment(context.Context, *CommentId) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedPostServiceServer) GetCommentByPostID(context.Context, *PostId) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentByPostID not implemented")
}
func (UnimplementedPostServiceServer) GetAllUserComments(context.Context, *CommentId) (*CommentAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUserComments not implemented")
}
func (UnimplementedPostServiceServer) GetMostlikeCommentPost(context.Context, *PostId) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMostlikeCommentPost not implemented")
}
func (UnimplementedPostServiceServer) mustEmbedUnimplementedPostServiceServer() {}

// UnsafePostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostServiceServer will
// result in compilation errors.
type UnsafePostServiceServer interface {
	mustEmbedUnimplementedPostServiceServer()
}

func RegisterPostServiceServer(s grpc.ServiceRegistrar, srv PostServiceServer) {
	s.RegisterService(&PostService_ServiceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*UpdateAPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetPostByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostByID(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListPosts(ctx, req.(*PostList))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_RemoveImageFromPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).RemoveImageFromPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_RemoveImageFromPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).RemoveImageFromPost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostCountry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetPostByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostByCountry(ctx, req.(*PostCountry))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_AddLikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikePost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).AddLikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_AddLikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).AddLikePost(ctx, req.(*LikePost))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteLikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteLikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_DeleteLikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteLikePost(ctx, req.(*LikeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_AddLikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).AddLikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_AddLikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).AddLikeComment(ctx, req.(*LikeId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteLikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteLikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_DeleteLikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteLikeComment(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetPostLikeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPostLikeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetPostLikeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPostLikeCount(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetCommentLikeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Like)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetCommentLikeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetCommentLikeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetCommentLikeCount(ctx, req.(*Like))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetUsersWhichLikePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetUsersWhichLikePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetUsersWhichLikePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetUsersWhichLikePost(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetUsersWhichLikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetUsersWhichLikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetUsersWhichLikeComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetUsersWhichLikeComment(ctx, req.(*CommentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreateComment(ctx, req.(*CommentPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAComment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdateComment(ctx, req.(*UpdateAComment))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetCommentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetCommentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetCommentByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetCommentByID(ctx, req.(*CommentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetCommentByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetCommentByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetCommentByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetCommentByUsername(ctx, req.(*UserPostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListComments(ctx, req.(*CommentList))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteComment(ctx, req.(*CommentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetCommentByPostID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetCommentByPostID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetCommentByPostID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetCommentByPostID(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetAllUserComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetAllUserComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetAllUserComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetAllUserComments(ctx, req.(*CommentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetMostlikeCommentPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetMostlikeCommentPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostService_GetMostlikeCommentPost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetMostlikeCommentPost(ctx, req.(*PostId))
	}
	return interceptor(ctx, in, info, handler)
}

// PostService_ServiceDesc is the grpc.ServiceDesc for PostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "post.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
		{
			MethodName: "GetPostByID",
			Handler:    _PostService_GetPostByID_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _PostService_ListPosts_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
		{
			MethodName: "RemoveImageFromPost",
			Handler:    _PostService_RemoveImageFromPost_Handler,
		},
		{
			MethodName: "GetPostByCountry",
			Handler:    _PostService_GetPostByCountry_Handler,
		},
		{
			MethodName: "AddLikePost",
			Handler:    _PostService_AddLikePost_Handler,
		},
		{
			MethodName: "DeleteLikePost",
			Handler:    _PostService_DeleteLikePost_Handler,
		},
		{
			MethodName: "AddLikeComment",
			Handler:    _PostService_AddLikeComment_Handler,
		},
		{
			MethodName: "DeleteLikeComment",
			Handler:    _PostService_DeleteLikeComment_Handler,
		},
		{
			MethodName: "GetPostLikeCount",
			Handler:    _PostService_GetPostLikeCount_Handler,
		},
		{
			MethodName: "GetCommentLikeCount",
			Handler:    _PostService_GetCommentLikeCount_Handler,
		},
		{
			MethodName: "GetUsersWhichLikePost",
			Handler:    _PostService_GetUsersWhichLikePost_Handler,
		},
		{
			MethodName: "GetUsersWhichLikeComment",
			Handler:    _PostService_GetUsersWhichLikeComment_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _PostService_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _PostService_UpdateComment_Handler,
		},
		{
			MethodName: "GetCommentByID",
			Handler:    _PostService_GetCommentByID_Handler,
		},
		{
			MethodName: "GetCommentByUsername",
			Handler:    _PostService_GetCommentByUsername_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _PostService_ListComments_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _PostService_DeleteComment_Handler,
		},
		{
			MethodName: "GetCommentByPostID",
			Handler:    _PostService_GetCommentByPostID_Handler,
		},
		{
			MethodName: "GetAllUserComments",
			Handler:    _PostService_GetAllUserComments_Handler,
		},
		{
			MethodName: "GetMostlikeCommentPost",
			Handler:    _PostService_GetMostlikeCommentPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Protocol-buffers/post/post.proto",
}
